=== Gergoybey/documents/modules/config.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/holders.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE config SYSTEM "config.dtd">

    <pola>
    ...
    </pola>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT config (pole)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT pole (nazwa?,wartosc?)>
<!ATTLIST pole
    etykieta CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT wartosc (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nazwa (#PCDATA)>

=== Gergoybey/documents/templates/przykład/config.xml
<?xml version="1.0" ?>
<!DOCTYPE config SYSTEM "../../modules/config.dtd">

<config>
    <pole etykieta="_DATE_">
        <nazwa>Data</nazwa>
        <wartosc>.2016r.</wartosc>
    </pole>
    <pole etykieta="_WHERE_">
        <nazwa>Adres</nazwa>
        <wartosc>ul. - Rumia</wartosc>
    </pole>
    <pole etykieta="_ANAME_">
        <nazwa>Autor</nazwa>
        <wartosc>Adrian Pieper</wartosc>
    </pole>
    <pole etykieta="_NAME_"> 
        <nazwa>Kto</nazwa>
        <wartosc>?</wartosc>
    </pole>
    <pole etykieta="_EWHERE_">
        <nazwa>Gdzie</nazwa>
        <wartosc>?</wartosc>
    </pole>
    <pole etykieta="_EDATE_">
        <nazwa>Kiedy</nazwa>
        <wartosc>.2016r.</wartosc>
    </pole>
</config>
